/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.home;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import modelo.ProfessorVO;
import servicos.ProfessorServicos;
import servicos.ServicosFactory;
import view.panel.CadastrarAluno;
import view.panel.CadastrarCronograma;
import view.panel.CadastrarProfessor;
import view.panel.ConsultarAluno;
import view.panel.ConsultarCronograma;
import view.panel.ConsultarProfessor;

/**
 *
 * @author proxc
 */
public class Home20 extends javax.swing.JFrame {

    private CardLayout cardLayout;

        List<JPanel> listaDeInc;
        List<JPanel> listaDebtn;
    
    
    /**
     * Creates new form Home20
     */
    public Home20() {

        initComponents();
        
        
        
        listaDeInc = new ArrayList<>();
        listaDeInc.add(ind_consultaAluno);
        listaDeInc.add(ind_CadastraAluno);
        listaDeInc.add(ind_CadastraProfessor);
        listaDeInc.add(ind_CadastraCronograma);
        listaDeInc.add(ind_ConsultaProfessor);
        listaDeInc.add(ind_ConsultaCronograma);
        
        listaDebtn = new ArrayList<>();
        listaDebtn.add(btn_ConsultarAluno);
        listaDebtn.add(btn_CadastrarProfessor);
        listaDebtn.add(btn_CadastrarAluno);
        listaDebtn.add(btn_consultar_professor);
        listaDebtn.add(btn_consultarCronograma);  
        listaDebtn.add(btn_CadastrarCronograma);
        
        CadastrarAluno cda = new CadastrarAluno();
        CadastrarProfessor cdp = new CadastrarProfessor();
        CadastrarCronograma cdc = new CadastrarCronograma();
        
        ConsultarAluno cca = new ConsultarAluno();
        ConsultarProfessor ccp = new ConsultarProfessor();
        ConsultarCronograma ccc = new ConsultarCronograma();
        
        pnlRight.add(cda, "cadastrarAluno");
        pnlRight.add(cdp, "cadastrarProfessor");
        pnlRight.add(cdc, "cadastrarCronograma");
                        
        pnlRight.add(cca, "consultarAluno");
        pnlRight.add(ccp, "consultarProfessor");
        pnlRight.add(ccc, "consultarCronograma");
    
        
        Home20.this.getRootPane().setBorder(new LineBorder(new Color(76, 41, 211)));
    
        
        lblTitle.setText("Senac");
        cardLayout = (CardLayout) pnlRight.getLayout();

        if (OSUtils.getOSType() == OSUtils.OSType.MacOS) {
            pnlTop.remove(pnlTitle);
            pnlTop.remove(pnlRight);

            pnlTop.add(pnlTitle, BorderLayout.EAST);
            pnlTop.add(pnlActions, BorderLayout.WEST);

            pnlActions.remove(lblClose);
            pnlActions.remove(lblMaximize);
            pnlActions.remove(lblMinimize);

            pnlActions.add(lblClose);
            pnlActions.add(lblMaximize);
            pnlActions.add(lblMinimize);

            pnlTitle.remove(lblTitle);
            pnlTitle.setLayout(new FlowLayout(FlowLayout.RIGHT, 10, 8));
            pnlTitle.add(lblTitle);

        }
        if (OSUtils.getOSType() == OSUtils.OSType.Windows) {
            pnlTop.remove(pnlTitle);
            pnlTop.remove(pnlRight);

            pnlTop.add(pnlTitle, BorderLayout.WEST);
            pnlTop.add(pnlActions, BorderLayout.EAST);

            pnlActions.remove(lblClose);
            pnlActions.remove(lblMaximize);
            pnlActions.remove(lblMinimize);

            pnlActions.add(lblMinimize);
            pnlActions.add(lblMaximize);
            pnlActions.add(lblClose);

            pnlTitle.remove(lblTitle);
            pnlTitle.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 8));
            pnlTitle.add(lblTitle);

        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlActions = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblMaximize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlParent = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_ConsultarAluno = new javax.swing.JPanel();
        ind_consultaAluno = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_consultar_professor = new javax.swing.JPanel();
        ind_ConsultaProfessor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_consultarCronograma = new javax.swing.JPanel();
        ind_ConsultaCronograma = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_CadastrarAluno = new javax.swing.JPanel();
        ind_CadastraAluno = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_CadastrarProfessor = new javax.swing.JPanel();
        ind_CadastraProfessor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_CadastrarCronograma = new javax.swing.JPanel();
        ind_CadastraCronograma = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_CadastrarAluno1 = new javax.swing.JPanel();
        ind_CadastraAluno1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_CadastrarAluno2 = new javax.swing.JPanel();
        ind_CadastraAluno2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Title Frame Test");
        setLocationByPlatform(true);
        setUndecorated(true);

        pnlTop.setBackground(new java.awt.Color(204, 102, 0));
        pnlTop.setPreferredSize(new java.awt.Dimension(1024, 30));
        pnlTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopMouseDragged(evt);
            }
        });
        pnlTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTopMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopMousePressed(evt);
            }
        });
        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlActions.setBackground(new java.awt.Color(204, 102, 0));
        pnlActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home/images/icons8_minus_18px_1.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        pnlActions.add(lblMinimize);

        lblMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home/images/icons8_rectangle_stroked_18px.png"))); // NOI18N
        lblMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMaximizeMousePressed(evt);
            }
        });
        pnlActions.add(lblMaximize);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home/images/icons8_multiply_18px_1.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        pnlActions.add(lblClose);

        pnlTop.add(pnlActions, java.awt.BorderLayout.LINE_END);

        pnlTitle.setBackground(new java.awt.Color(204, 102, 0));
        pnlTitle.setPreferredSize(new java.awt.Dimension(200, 30));
        pnlTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 8));

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Senac");
        pnlTitle.add(lblTitle);

        pnlTop.add(pnlTitle, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlParent.setLayout(new java.awt.BorderLayout());

        sidepane.setBackground(new java.awt.Color(255, 102, 0));
        sidepane.setForeground(new java.awt.Color(255, 255, 255));
        sidepane.setPreferredSize(new java.awt.Dimension(250, 200));
        sidepane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidepaneMouseDragged(evt);
            }
        });
        sidepane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidepaneMousePressed(evt);
            }
        });

        btn_ConsultarAluno.setBackground(new java.awt.Color(255, 102, 0));
        btn_ConsultarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ConsultarAlunoMousePressed(evt);
            }
        });
        btn_ConsultarAluno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_consultaAluno.setOpaque(false);
        ind_consultaAluno.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_consultaAlunoLayout = new javax.swing.GroupLayout(ind_consultaAluno);
        ind_consultaAluno.setLayout(ind_consultaAlunoLayout);
        ind_consultaAlunoLayout.setHorizontalGroup(
            ind_consultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_consultaAlunoLayout.setVerticalGroup(
            ind_consultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_ConsultarAluno.add(ind_consultaAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Alunos");
        btn_ConsultarAluno.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senac");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pedagogia");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("V2.11");

        btn_consultar_professor.setBackground(new java.awt.Color(255, 102, 0));
        btn_consultar_professor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_consultar_professorMousePressed(evt);
            }
        });
        btn_consultar_professor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_ConsultaProfessor.setOpaque(false);
        ind_ConsultaProfessor.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_ConsultaProfessorLayout = new javax.swing.GroupLayout(ind_ConsultaProfessor);
        ind_ConsultaProfessor.setLayout(ind_ConsultaProfessorLayout);
        ind_ConsultaProfessorLayout.setHorizontalGroup(
            ind_ConsultaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_ConsultaProfessorLayout.setVerticalGroup(
            ind_ConsultaProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_consultar_professor.add(ind_ConsultaProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Professores");
        btn_consultar_professor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btn_consultarCronograma.setBackground(new java.awt.Color(255, 102, 0));
        btn_consultarCronograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_consultarCronogramaMousePressed(evt);
            }
        });
        btn_consultarCronograma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_ConsultaCronograma.setOpaque(false);
        ind_ConsultaCronograma.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_ConsultaCronogramaLayout = new javax.swing.GroupLayout(ind_ConsultaCronograma);
        ind_ConsultaCronograma.setLayout(ind_ConsultaCronogramaLayout);
        ind_ConsultaCronogramaLayout.setHorizontalGroup(
            ind_ConsultaCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_ConsultaCronogramaLayout.setVerticalGroup(
            ind_ConsultaCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_consultarCronograma.add(ind_ConsultaCronograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cronogramas");
        btn_consultarCronograma.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Turmas");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CADASTROS");

        btn_CadastrarAluno.setBackground(new java.awt.Color(255, 102, 0));
        btn_CadastrarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CadastrarAlunoMousePressed(evt);
            }
        });
        btn_CadastrarAluno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_CadastraAluno.setOpaque(false);
        ind_CadastraAluno.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_CadastraAlunoLayout = new javax.swing.GroupLayout(ind_CadastraAluno);
        ind_CadastraAluno.setLayout(ind_CadastraAlunoLayout);
        ind_CadastraAlunoLayout.setHorizontalGroup(
            ind_CadastraAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_CadastraAlunoLayout.setVerticalGroup(
            ind_CadastraAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_CadastrarAluno.add(ind_CadastraAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Alunos");
        btn_CadastrarAluno.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btn_CadastrarProfessor.setBackground(new java.awt.Color(255, 102, 0));
        btn_CadastrarProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CadastrarProfessorMousePressed(evt);
            }
        });
        btn_CadastrarProfessor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_CadastraProfessor.setOpaque(false);
        ind_CadastraProfessor.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_CadastraProfessorLayout = new javax.swing.GroupLayout(ind_CadastraProfessor);
        ind_CadastraProfessor.setLayout(ind_CadastraProfessorLayout);
        ind_CadastraProfessorLayout.setHorizontalGroup(
            ind_CadastraProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_CadastraProfessorLayout.setVerticalGroup(
            ind_CadastraProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_CadastrarProfessor.add(ind_CadastraProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Professores");
        btn_CadastrarProfessor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btn_CadastrarCronograma.setBackground(new java.awt.Color(255, 102, 0));
        btn_CadastrarCronograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CadastrarCronogramaMousePressed(evt);
            }
        });
        btn_CadastrarCronograma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_CadastraCronograma.setOpaque(false);
        ind_CadastraCronograma.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_CadastraCronogramaLayout = new javax.swing.GroupLayout(ind_CadastraCronograma);
        ind_CadastraCronograma.setLayout(ind_CadastraCronogramaLayout);
        ind_CadastraCronogramaLayout.setHorizontalGroup(
            ind_CadastraCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_CadastraCronogramaLayout.setVerticalGroup(
            ind_CadastraCronogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_CadastrarCronograma.add(ind_CadastraCronograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cronogramas");
        btn_CadastrarCronograma.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONSULTAS");
        jLabel11.setToolTipText("");

        btn_CadastrarAluno1.setBackground(new java.awt.Color(255, 102, 0));
        btn_CadastrarAluno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CadastrarAluno1MousePressed(evt);
            }
        });
        btn_CadastrarAluno1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_CadastraAluno1.setOpaque(false);
        ind_CadastraAluno1.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_CadastraAluno1Layout = new javax.swing.GroupLayout(ind_CadastraAluno1);
        ind_CadastraAluno1.setLayout(ind_CadastraAluno1Layout);
        ind_CadastraAluno1Layout.setHorizontalGroup(
            ind_CadastraAluno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_CadastraAluno1Layout.setVerticalGroup(
            ind_CadastraAluno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_CadastrarAluno1.add(ind_CadastraAluno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Listão");
        btn_CadastrarAluno1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btn_CadastrarAluno2.setBackground(new java.awt.Color(255, 102, 0));
        btn_CadastrarAluno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CadastrarAluno2MousePressed(evt);
            }
        });
        btn_CadastrarAluno2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_CadastraAluno2.setOpaque(false);
        ind_CadastraAluno2.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_CadastraAluno2Layout = new javax.swing.GroupLayout(ind_CadastraAluno2);
        ind_CadastraAluno2.setLayout(ind_CadastraAluno2Layout);
        ind_CadastraAluno2Layout.setHorizontalGroup(
            ind_CadastraAluno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_CadastraAluno2Layout.setVerticalGroup(
            ind_CadastraAluno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btn_CadastrarAluno2.add(ind_CadastraAluno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cadastrar");
        btn_CadastrarAluno2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_ConsultarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_consultar_professor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_consultarCronograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_CadastrarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_CadastrarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(sidepaneLayout.createSequentialGroup()
                                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addComponent(btn_CadastrarCronograma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(btn_CadastrarAluno1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addComponent(btn_CadastrarAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_consultar_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_consultarCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_CadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CadastrarCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CadastrarAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CadastrarAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pnlParent.add(sidepane, java.awt.BorderLayout.LINE_START);

        pnlRight.setLayout(new java.awt.CardLayout());

        jLabel4.setText("Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel4)
                .addContainerGap(1142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel4)
                .addContainerGap(576, Short.MAX_VALUE))
        );

        pnlRight.add(jPanel1, "card2");

        pnlParent.add(pnlRight, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlParent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xy, xx;

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Nome", "Valor Custo", "quantidade"}
    );
    
    private void selectButton(JPanel btn, JPanel inc){
        
      
        for (JPanel panel : listaDeInc) {
            if(panel == inc)
            panel.setOpaque(true);
            else{// ou outra propriedade que deseja modificar
            panel.setOpaque(false);
            }
        }
        for (JPanel panel : listaDebtn) {
            if(panel == btn)
                setColor(panel); // ou outra propriedade que deseja modificar
            else{
                resetColor(panel);
                        }
        }
       
    }
    
    private void sidepaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepaneMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_sidepaneMouseDragged

    private void sidepaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepaneMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_sidepaneMousePressed

    private void btn_ConsultarAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConsultarAlunoMousePressed
        // TODO add your handling code here:
        selectButton(btn_ConsultarAluno, ind_consultaAluno);

        cardLayout.show(pnlRight, "consultarAluno");

    }//GEN-LAST:event_btn_ConsultarAlunoMousePressed

    private void btn_consultar_professorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultar_professorMousePressed
        // TODO add your handling code here:
        selectButton(btn_consultar_professor, ind_ConsultaProfessor);

        cardLayout.show(pnlRight, "consultarProfessor");

    }//GEN-LAST:event_btn_consultar_professorMousePressed

    private void btn_consultarCronogramaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarCronogramaMousePressed
        // TODO add your handling code here:
        selectButton(btn_consultarCronograma, ind_ConsultaCronograma);
        
        cardLayout.show(pnlRight,"consultarCronograma");

    }//GEN-LAST:event_btn_consultarCronogramaMousePressed

    private void btn_CadastrarAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CadastrarAlunoMousePressed
        // TODO add your handling code here:
        selectButton(btn_CadastrarAluno, ind_CadastraAluno);
        
        cardLayout.show(pnlRight,"cadastrarAluno");
    }//GEN-LAST:event_btn_CadastrarAlunoMousePressed

    private void btn_CadastrarProfessorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CadastrarProfessorMousePressed
        // TODO add your handling code here:
        selectButton(btn_CadastrarProfessor, ind_CadastraProfessor);

        cardLayout.show(pnlRight, "cadastrarProfessor");
    }//GEN-LAST:event_btn_CadastrarProfessorMousePressed


    private void lblMaximizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizeMousePressed
        if (Home20.this.getExtendedState() == MAXIMIZED_BOTH) {
            Home20.this.setExtendedState(JFrame.NORMAL);
        } else {
            Home20.this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_lblMaximizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        Home20.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void pnlTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTopMousePressed

    private void pnlTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTopMouseDragged

    private void pnlTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (Home20.this.getExtendedState() == MAXIMIZED_BOTH) {
                Home20.this.setExtendedState(JFrame.NORMAL);
            } else {
                Home20.this.setExtendedState(MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_pnlTopMouseClicked

    private void btn_CadastrarCronogramaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CadastrarCronogramaMousePressed
        selectButton(btn_CadastrarCronograma, ind_CadastraCronograma);

        cardLayout.show(pnlRight, "cadastrarCronograma");
    }//GEN-LAST:event_btn_CadastrarCronogramaMousePressed

    private void btn_CadastrarAluno1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CadastrarAluno1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CadastrarAluno1MousePressed

    private void btn_CadastrarAluno2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CadastrarAluno2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CadastrarAluno2MousePressed

    // set and reset color
    void setColor(JPanel panel) {
        panel.setBackground(new Color(40, 37, 38));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(255, 102, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home20().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_CadastrarAluno;
    private javax.swing.JPanel btn_CadastrarAluno1;
    private javax.swing.JPanel btn_CadastrarAluno2;
    private javax.swing.JPanel btn_CadastrarCronograma;
    private javax.swing.JPanel btn_CadastrarProfessor;
    private javax.swing.JPanel btn_ConsultarAluno;
    private javax.swing.JPanel btn_consultarCronograma;
    private javax.swing.JPanel btn_consultar_professor;
    private javax.swing.JPanel ind_CadastraAluno;
    private javax.swing.JPanel ind_CadastraAluno1;
    private javax.swing.JPanel ind_CadastraAluno2;
    private javax.swing.JPanel ind_CadastraCronograma;
    private javax.swing.JPanel ind_CadastraProfessor;
    private javax.swing.JPanel ind_ConsultaCronograma;
    private javax.swing.JPanel ind_ConsultaProfessor;
    private javax.swing.JPanel ind_consultaAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMaximize;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
