/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import javax.swing.JOptionPane;
import modelo.ProfessorVO;
import servicos.ProfessorServicos;

/**
 *
 * @author 292100561
 */
public class CadastrarProfessor extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarProfessor
     */
    public CadastrarProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNomeValue = new javax.swing.JTextField();
        jtfCpfValue = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jtfEmailValue = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        jtfTelefoneValue = new javax.swing.JTextField();
        jtfDataNascValue = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jlDataNasc = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jtfEnderecoValue = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jtfNomeValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtfCpfValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEmail.setText("Email");

        jlCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCpf.setText("CPF");

        jtfEmailValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEndereco.setText("Endereço");

        jtfTelefoneValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtfDataNascValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNome.setText("Nome (Completo)");

        jlDataNasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlDataNasc.setText("Data Nascimento");

        jlTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTelefone.setText("Telefone");

        jtfEnderecoValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfEnderecoValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEnderecoValueActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setText("CADASTRAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel2.setText("TELA PARA CADASTRAR ");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel3.setText("PROFESSORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEmail)
                    .addComponent(jlDataNasc)
                    .addComponent(jlNome))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfEmailValue, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jtfNomeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jtfDataNascValue, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTelefone)
                    .addComponent(jlEndereco)
                    .addComponent(jlCpf))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCpfValue)
                    .addComponent(jtfTelefoneValue)
                    .addComponent(jtfEnderecoValue))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEnderecoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNome)
                    .addComponent(jlEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmailValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTelefoneValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEmail)
                    .addComponent(jlTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataNascValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCpfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDataNasc)
                    .addComponent(jlCpf))
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void cadastrar(){
            try {
                ProfessorVO pVO = new ProfessorVO();

                pVO.setNome(jtfNomeValue.getText());
                pVO.setEmail(jtfEmailValue.getText());
                pVO.setData_nascimento(jtfDataNascValue.getText());
                pVO.setEndereco(jtfEnderecoValue.getText());
                pVO.setTelefone(jtfTelefoneValue.getText());
                pVO.setCpf(jtfCpfValue.getText());

            
                /*
                Enviar o objeto pVO para o banco de dados,
                mas o envio é através da Servicos,
                porém antes passa pela DAO.
                */
                ProfessorServicos ps = servicos.ServicosFactory.getProfessorServicos();

                //Chamndo o método
                ps.cadastrarProfessor(pVO);

                //Retorno para o usuário
                JOptionPane.showMessageDialog(this, "Professor Cadastrado com sucesso!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro! GUICadProfessors " + e.getMessage());
            }
        }//fim do método cadastrar
    
    private void limpar(){
        jtfNomeValue.setText("");
        jtfEmailValue.setText("");
        jtfDataNascValue.setText("");
        jtfEnderecoValue.setText("");
        jtfTelefoneValue.setText("");
        jtfCpfValue.setText("");
        
    }
    
    
    
    private void jtfEnderecoValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEnderecoValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEnderecoValueActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        cadastrar();
        limpar();
    }//GEN-LAST:event_jPanel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlDataNasc;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JTextField jtfCpfValue;
    private javax.swing.JTextField jtfDataNascValue;
    private javax.swing.JTextField jtfEmailValue;
    private javax.swing.JTextField jtfEnderecoValue;
    private javax.swing.JTextField jtfNomeValue;
    private javax.swing.JTextField jtfTelefoneValue;
    // End of variables declaration//GEN-END:variables
}
